# Generated by Django 4.2.3 on 2023-07-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
