# Generated by Django 4.2.3 on 2023-07-22 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_assistance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
