# Generated by Django 4.2.3 on 2023-07-22 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_assistance_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistance',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 22)),
        ),
    ]
