# Generated by Django 4.2.4 on 2023-08-07 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('src', '0005_alter_assistance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='id_reglamento',
            new_name='idRegulation',
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
