# Generated by Django 4.2.4 on 2023-08-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_rename_id_reglamento_blacklist_idregulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='idBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.gymbranch'),
        ),
    ]
