# Generated by Django 4.2.3 on 2023-07-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_blacklist_iduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='id_reglamento',
            new_name='idRegulation',
        ),
    ]
