# Generated by Django 4.2.3 on 2023-07-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=200)),
                ('start_hours', models.TimeField()),
                ('final_hours', models.TimeField()),
                ('day', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=False)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.users')),
            ],
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(null=True)),
                ('day', models.DateField()),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.users')),
            ],
        ),
    ]
