# Generated by Django 4.2.3 on 2023-07-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_assistance_id_alter_coach_id_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
